feat: Version data class
Chouten-App/Chouten-Android-Clean pull request #36
Opened 2023-12-12 17:24 UTC by Adolar0042

2023-12-12 17:55 UTC, Adolar0042 commented
waiting for @TobyBridle to fix a crash so I can actually test this

2024-01-12 13:57 UTC, TobyBridle commented
Sorry for taking so long to fix, but should all be good now :)

2024-01-18 18:37 UTC, TobyBridle reviewed
test

2024-01-18 19:27 UTC, TobyBridle requested changes

2024-01-18 19:27 UTC, TobyBridle commented on app/src/main/java/com/chouten/app/domain/use_case/module_use_cases/AddModuleUseCase.kt
> +                    if (module.version < it.second.version) { // old module version < new module version
Here the "old" module is actually newer. We should remove the old version instead.
```suggestion
                    if (module.version < it.second.version) { // old module version > new module version
                         // Delete the old module
                            if (DocumentFile.fromSingleUri(mContext, newModuleUri)?.delete() == false) {
```

2024-01-18 19:27 UTC, TobyBridle commented on app/src/main/java/com/chouten/app/domain/use_case/module_use_cases/AddModuleUseCase.kt
> -                        // Module being installed is older than the existing module
Module being installed is NEWER than the existing module.
```suggestion
    // Module being installed is newer than the existing module
    else -> {
        safeException(
            IllegalArgumentException("Module ${module.name} (${module.id}) is older than the existing module"),
            IOException("Could not delete module ${it.second.name} (${it.second.id})"),
            it.first
        )
    }
```

2024-01-18 19:28 UTC, TobyBridle commented
Please could you also reformat after submitting the changes

2024-01-18 23:29 UTC, merged

2024-01-18 23:29 UTC, TobyBridle commented
LGTM thanks :+1: